name: Publish to NuGet.org
on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack -c Release -o packages
    - name: Publish
      run: |
       dotnet nuget push "./packages/*.nupkg" --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}        
